### PR TITLE
Revertible thunks as function II: fix recursive overriding

### LINKED ISSUE #908: Recursive overriding is nonassociative
Recursive record overriding is currently nonassociative:
```
let correct_ =
{
    foo = "Overridden",
} & {
  config | {
    output | {
        value | Str,
    }
  },
} & {
  foo | Str
    | default = "blub",

  config.output.value = foo,
} in
let wrong_ =
{
    foo = "Overridden",
} & ({
  config | {
    output | {
        value | Str,
    }
  },
} & {
  foo | Str
    | default = "blub",

  config.output.value = foo,
}) in
{
  correct = correct_,
  wrong = wrong_,
}
```
yields
```
{
  wrong = { foo = "Overridden", config = { output = { value = "blub" } } },
  correct = { foo = "Overridden", config = { output = { value = "Overridden" } } } 
}
```

The semantics of record overriding should always be associative.

**Environment**
 - OS name + version: NixOS unstable
 - Version of the code: c13c51f51b61ce7617cee7796dc4113c3a1567af

### PR DESCRIPTION
**Pull request by yannham**
# Revertible thunks are functions

Closes #908.

Follow-up of #924: bring the presentation of revertible thunks as just functions  memoization devices to its logical conclusion by providing helper to explicitly rebuild the represented function and apply it. This explicit application was required to fix recursive overriding in the general case, see #908. Now, the implementation faithfully expresses general merging of recursive fields as `common_field = fun self => (left_field self) & (right_field self)`, when recursive record fields are understood as functions of `self` (representing the ambient record).

## Revertible thunks representation

This PR also reworks the representation of revertible thunks. They used to store the cached data as an `Rc<Closure>`, initialized as soon as the revertible thunks was initialized. This doesn't model revertible thunks faithfully: the cached value should be owned (as it is for normal thunks), and as long as the revertible thunks hasn't be "patched" (or, when seen as a function, applied), the cached value is meaningless and may contain free variables, id est unbound identifiers.

The cached value should never be used before full initialization. This PR sets the cached value to be an `Option<Closure>`, and to panic if it used before initialization. It also ensures that initialization is done only once. The previous implementation wouldn't complain about such violation. Note that we have no choice to perform the construction of a revertible thunks in two steps, and thus observe a transitory state where the cached value is not initialized, because we are potentially building cyclic values. However, if the implementation is correct, the state where the cached value is set to `None` shouldn't really be observable.

### CODE REVIEW

File: src/eval/lazy.rs [hunk 1]
```diff
@@ -121,41 +131,149 @@ impl ThunkData {
...
     }
 
     /// Consume the data and return the cached closure.
     pub fn into_closure(self) -> Closure {
         match self.inner {
             InnerThunkData::Standard(closure) => closure,
-            InnerThunkData::Revertible { orig, cached, .. } => {
-                std::mem::drop(orig);
-                Rc::try_unwrap(cached).unwrap_or_else(|rc| (*rc).clone())
+            // Nothing should access the cached value of a revertible thunks before the cached
```
Comment (yannham) [inline src/eval/lazy.rs:266]:
```suggestion
            // Nothing should access the cached value of a revertible thunk before the cached
```

File: src/eval/lazy.rs [hunk 2]
```diff
@@ -333,6 +459,95 @@ impl Thunk {
...
 
+    pub fn build_cached(&mut self, rec_env: &[(Ident, Thunk)]) {
+        self.data.borrow_mut().init_cached(rec_env)
+    }
+
+    /// Revert a thunk, abstract over its dependencies to get back a function, and apply the
+    /// function to the given variables. The function part is allocated in a new fresh thunk,
+    /// stored as a generated variable, with the same environment as the original expression.
+    ///
+    /// Recall that revertible thunks are just a memoization mechanism) for function application.
```
Comment (yannham) [inline src/eval/lazy.rs:470]:
```suggestion
    /// Recall that revertible thunks are just a memoization mechanism for function application.
```

File: src/eval/lazy.rs [hunk 3]
```diff
@@ -333,6 +459,95 @@ impl Thunk {
...
+    /// manipulate the body of the function directly (which is what is stored inside the `orig`
+    /// field).
+    ///
+    /// However, in the general case of merging two record fields which may be both recursive (i.e.
+    /// which may contain a revertible thunk), we have to use the explicit function representation
+    /// and apply it to variables, which correspond to the fields of the recursive record being
+    /// built by merging.
+    ///
+    /// `saturate`:
+    /// - abstract the original expression of the underlying revertible thunk, forming a function.
```
Comment (yannham) [inline src/eval/lazy.rs:482]:
```suggestion
    /// - abstracts the original expression of the underlying revertible thunk, forming a function.
```

File: src/eval/lazy.rs [hunk 4]
```diff
@@ -333,6 +459,95 @@ impl Thunk {
...
+    /// - store this function in a fresh standard thunk
```
Comment (yannham) [inline src/eval/lazy.rs:483]:
```suggestion
    /// - stores this function in a fresh standard thunk
```

File: src/eval/lazy.rs [hunk 5]
```diff
@@ -333,6 +459,95 @@ impl Thunk {
...
+    /// - return the application of this function to the provided record field names (as variables)
```
Comment (yannham) [inline src/eval/lazy.rs:484]:
```suggestion
    /// - returns the application of this function to the provided record field names (as variables)
```

File: src/eval/lazy.rs [hunk 6]
```diff
@@ -333,6 +459,95 @@ impl Thunk {
...
+    ///
+    /// Non revertible thunks can be seen as a special case of revertible thunks with no
+    /// dependencies. Thus the abstraction and application are zero-ary, and the result is just the
+    /// current thunk closurized in `env` as a fresh variable.
+    ///
+    /// # Example
+    ///
+    /// If `orig` is `foo + bar + a` where `foo` and `bar` are thunk dependencies (hence are free
+    /// variables) and `a` is bound in the environment. Say the iterator represents the fields
+    /// `bar, b, foo` in that order. Then `rev_thunk_as_explicit_app`:
```
Comment (yannham) [inline src/eval/lazy.rs:511]:
```suggestion
    /// `bar, b, foo` in that order. Then `saturate`:
```

File: src/eval/lazy.rs [hunk 7]
```diff
@@ -121,41 +124,149 @@ impl ThunkData {
...
+            }
+        }
+    }
+
     /// Return a reference to the closure currently cached.
     pub fn closure(&self) -> &Closure {
         match self.inner {
             InnerThunkData::Standard(ref closure) => closure,
-            InnerThunkData::Revertible { ref cached, .. } => cached,
+            // Nothing should peek into a revertible thunks before the cached value has been
```
Comment (yannham) [inline src/eval/lazy.rs:228]:
```suggestion
            // Nothing should peek into a revertible thunk before the cached value has been
```

File: src/eval/merge.rs [hunk 8]
```diff
@@ -500,8 +500,110 @@ fn merge_doc(doc1: Option<String>, doc2: Option<String>) -> Option<String> {
     doc1.or(doc2)
 }
 
+/// Take the content of a record field, and saturate the potential revertible thunk with the given
+/// fields. See [crate::eval::lazy::Thunk::saturate].
+///
+/// If the expression is not a variable referring to a thunk (this can happen e.g. for numeric
+/// constant), we just return the term as it is, which falls into the zero dependencies special
```
Comment (yannham) [inline src/eval/merge.rs:507]:
```suggestion
/// constants), we just return the term as it is, which falls into the zero dependencies special
```

File: src/eval/merge.rs [hunk 9]
```diff
@@ -500,8 +500,110 @@ fn merge_doc(doc1: Option<String>, doc2: Option<String>) -> Option<String> {
...
+/// case as well.
```
Comment (yannham) [inline src/eval/merge.rs:508]:
```suggestion
/// case.
```

File: src/eval/merge.rs [hunk 10]
```diff
@@ -500,8 +500,110 @@ fn merge_doc(doc1: Option<String>, doc2: Option<String>) -> Option<String> {
...
+
+/// Take the current environment, two fields with their local environment, and return a term which
+/// is the merge of the two fields, closurized in the provided final environment.
+///
+/// The thunk allocated for the result is revertible if and only if at least one of the original
+/// thunk is (if one of the original value is overridable, then so is the merge of the two). In
+/// this case, the field dependencies are the union of the dependencies of each field.
+///
+/// The fields are saturaed (see [saturate]) to properly propagate recursive dependencies down to
+/// the `t1` and `t2` in the final, merged record.
```
Comment (yannham) [inline src/eval/merge.rs:547]:
```suggestion
/// `t1` and `t2` in the final, merged record.
```

File: src/eval/merge.rs [hunk 11]
```diff
@@ -500,8 +500,93 @@ fn merge_doc(doc1: Option<String>, doc2: Option<String>) -> Option<String> {
...
+    } else {
+        Ok(ThunkDeps::Empty)
+    }
+}
+
+/// Take the current environment, two fields with their local environment, and return a term which
+/// is the merge of the two fields, closurized in the provided final environment.
+///
+/// The thunk allocated for the result is revertible if and only if at least one of the original
+/// thunk is (if one of the original value is overridable, then so is the merge of the two). In
```
Comment (vkleen) [inline src/eval/merge.rs:543]:
```suggestion
/// thunks is (if one of the original values is overridable, then so is the merge of the two). In
```

File: src/eval/merge.rs [hunk 12]
```diff
@@ -500,8 +500,93 @@ fn merge_doc(doc1: Option<String>, doc2: Option<String>) -> Option<String> {
...
+/// this case, the field dependencies are the union of the dependencies of each field.
+///
+/// The fields are saturaed (see [saturate]) to properly propagate recursive dependencies down to
```
Comment (vkleen) [inline src/eval/merge.rs:546]:
```suggestion
/// The fields are saturated (see [saturate]) to properly propagate recursive dependencies down to
```

**Review by vkleen — APPROVED** [review]
I've just found some more typos in the comments. The logic seems good, as far as I can tell 👍

File: src/eval/merge.rs [hunk 13]
```diff
@@ -401,32 +384,41 @@ pub fn merge(
...
             let mut env = Environment::new();
 
-            for (field, t) in left.into_iter() {
-                m.insert(field, t.closurize(&mut env, env1.clone()));
-            }
-
-            for (field, t) in right.into_iter() {
-                m.insert(field, t.closurize(&mut env, env2.clone()));
-            }
+            // Merging recursive record is the one operation that may override recursive fields. To
```
Comment (yannham) [inline src/eval/merge.rs:396]:
```suggestion
            // Merging recursive records is the one operation that may override recursive fields. To
```

**Review by matthew-healy — COMMENTED** [review]
As far as I can tell, this looks good, though I have to say my mental model for exactly what's going on & how it all fits together isn't great and as such I don't feel qualified to give an approving review.

I left one or two small comments but just for minor things. I don't think they need to block merging.

File: src/eval/lazy.rs [hunk 14]
```diff
@@ -121,41 +124,149 @@ impl ThunkData {
...
+            // value has been constructed. This is an invariant that MUST be maintained by the
+            // interpreter
+            //
+            // `cached` set to `None` solely exists because we need to first allocate all the
+            // revertible thunks corresponding to a recursive record, and only then can we patch
+            // them (build the cached value) in a second step. But calling to
+            // [`ThunkData::new_rev`] followed by [`ThunkData::build_cached_value`] should be logically
+            // seen as just one construction operation.
+            InnerThunkData::Revertible { cached, .. } => {
+                cached.expect("tried to get data from a revertible thunk without a cached value")
```
[the remark this answers is not in the document]
Comment (yannham) [reply src/eval/lazy.rs:269]: Are you talking about the comment or the error message inside `expect` ? I imagine you meant the latter, in which case I agree.

File: src/eval/lazy.rs [hunk 15]
```diff
@@ -333,6 +445,95 @@ impl Thunk {
...
+            data: Rc::new(RefCell::new(
+                inner.revthunk_as_explicit_fun(fields.clone().filter(&mut deps_filter)),
+            )),
+            ident_kind: self.ident_kind,
+        };
+
+        let fresh_var = Ident::fresh();
+        env.insert(fresh_var, thunk_as_function);
+
+        let as_function = RichTerm::from(Term::Var(fresh_var));
```
[the remark this answers is not in the document]
Comment (yannham) [reply src/eval/lazy.rs:529]: Mh, that's a hard one. It's as a function as a var :) as the var is the closurized version of the function. Maybe `as_function_closurized`?

File: src/eval/lazy.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (matthew-healy) [reply src/eval/lazy.rs:269]: I actually meant _both_. I'm suggesting combining them so that the comment _is_ the error message passed to expect. I'm not sure it's a perfect solution, but I can definitely see a future where the comment gets changed in one place but gets missed in others. 

That said, I completely understand if you decide not to do this, as it does mean that devs need to go look up the static string definition to find the info that's currently in the comment...

File: src/eval/lazy.rs (hunk 15 above)
[the remark this answers is not in the document]
Comment (matthew-healy) [reply src/eval/lazy.rs:529]: Yeah, I think that's slightly clearer. It just confused me a little to see `as_function` being assigned to a `Term::Var`. :sweat_smile:

File: src/eval/lazy.rs [hunk 16]
```diff
@@ -121,41 +124,149 @@ impl ThunkData {
...
+                );
+
+                let mut new_cached = Closure::clone(orig);
+
+                match deps {
+                    Some(deps) if deps.is_empty() => (),
+                    Some(deps) => new_cached
+                        .env
+                        .extend(rec_env.iter().filter(|(id, _)| deps.contains(id)).cloned()),
+                    None => new_cached.env.extend(rec_env.iter().cloned()),
```
[the remark this answers is not in the document]
Comment (yannham) [reply src/eval/lazy.rs:181]: Tried that, but the diff is bigger than I would like. Will do so in a follow-up PR.

File: src/eval/lazy.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (yannham) [reply src/eval/lazy.rs:269]: Mmh, I think I like the idea of the comment being in the right place, directly accessible. The text showed in `expect` doesn't have exactly the same purpose. I'll still extract it in a separate variable though
