### PR TITLE
Fix evaluation order of record pattern matches, and related ident leakage

### LINKED ISSUE #2450: Breaking change in match statement evaluation
**Describe the bug**
There's a breaking change in how match statements are evaluated in the master branch as of 2eea9b5c752c9cfb3fbab1c48a6a6a5faf296685
Seems like evaluation on some fields is being forced during pattern matching that weren't evaluated before.

**To Reproduce**
The following input works in 1.14.0 but not in master.
```nickel
let x = { has_number = false } in
{ has_number = x.has_number, test = x.number == 1 } |> match {
  { has_number = true, test = true } => "number == 1",
  { has_number = true, test = false } => "number != 1",
  { has_number = false, .. } => "N/A",
}
```
In 1.14.0, this evaluates to "N/A". In master, it fails because it tries to evaluate ```x.number == 1``` and tries to access a missing field.

**Expected behavior**
I would expect this to evaluate to "N/A" as it does in 1.14.0

### PR DESCRIPTION
**Pull request by jneem**
The issue was essentially that we were checking patterns in record fields in the wrong order. But fixing the order exposed another bug with bindings leaking into the wrong match arm (which fortunately I was already testing for).

Basically, I had thought that binding leakage could be avoided if we make sure never to shadow anything in the failure continuation. But while folding record (and array) pattern matching, the failure continuation becomes part of the success continuation. So in fact you need to avoid shadowing anything ever. This PR avoids shadowing by only using fresh vars during `CompilePart::compile_part`, and doing the real binding just before the match arm (or the guard, if there is one).

Fixes #2450.

### CODE REVIEW

File: core/src/term/pattern/compile.rs [hunk 1]
```diff
@@ -207,35 +195,44 @@ pub trait CompilePart {
...
+        bindings: &HashMap<LocIdent, LocIdent>,
     ) -> NickelValue;
 }
 
 impl CompilePart for Pattern {
     // Compilation of the top-level pattern wrapper. If there's an alias,
     // compiles to
     //
-    // pattern_data.compile(value_id, let <alias> = value_id in <match_cont>, <fail_cont>)
+    // pattern_data.compile(value_id, let %alias_id% = value_id in <match_cont>, <fail_cont>)
```
Comment (yannham) [inline core/src/term/pattern/compile.rs]: Nitpick: I don't think we use `%...%` syntax elsewhere in this file, as a meta-syntax. Reading like this, it looks like a Nickel operator, but it's not. I would suggest to either use `alias_id` like `value_id` after it, or `<alias_id>` if you think it better fits as a meta variable.

File: core/src/term/pattern/compile.rs [hunk 2]
```diff
@@ -438,7 +446,7 @@ impl CompilePart for RecordPattern {
 
         let match_cont = if let TailPattern::Capture(tail) = self.tail {
             // let
-            //   <tail> = (%record/remove_with_opts% field0 (%record/remove_with_opts% field1 local_value_id) ... )
+            //   %tail_id% = (%record/remove_with_opts% field0 (%record/remove_with_opts% field1 local_value_id) ... )
```
Comment (yannham) [inline core/src/term/pattern/compile.rs]: Same remark about meta syntax.

File: core/src/term/pattern/compile.rs [hunk 3]
```diff
@@ -836,9 +858,18 @@ impl Compile for MatchData {
...
+        // to fresh variables (e.g. `{ foo => %1, bar => %2 }`) if `foo` and
+        // `bar` are the variables bound by the current pattern. We pass
+        // this map to the pattern compilation so that it will bind `%1` to
+        // the expression that we'll eventually bind `foo` to.
+        // See `CompilePart::compile_part` for why we do this.
+        //
         // <for branch in branches.rev()
         //  - fail_cont is the accumulator
         // >
+        //    let foo = %1, bar = %2, <...other bindings> in
```
Comment (yannham) [inline core/src/term/pattern/compile.rs]: I think the let-biniding isn't actually put in the enclosing scope, but rather attached in `match_cont`, and _then_ compiled, right?

File: core/src/transform/desugar_destructuring.rs [hunk 4]
```diff
@@ -129,29 +130,35 @@ pub fn desugar_let(
...
         }
 
-        let bindings_record = NickelValue::term_posless(Term::rec_record(
-            Default::default(),
-            includes,
-            Vec::new(),
-            None,
-            false,
-        ));
+        let bindings_record = NickelValue::record_posless(RecordData {
```
Comment (yannham) [inline core/src/transform/desugar_destructuring.rs:145]: The documentation above still mentions `include`. It should be updated, I suppose.

File: core/src/term/pattern/compile.rs (hunk 1 above)
Comment (jneem) [reply core/src/term/pattern/compile.rs]: Fair enough. I was trying to hint that `%alias_id%` was a generated identifier and not the actual pattern variable. I've given up on hinting, and now write that out explicitly.

File: core/src/term/pattern/compile.rs (hunk 3 above)
Comment (jneem) [reply core/src/term/pattern/compile.rs]: Good point, fixed.
