### PR TITLE
Treat variables bound by record deconstruction like record static indexing

### LINKED ISSUE #1011: LSP server doesn't give completion on pattern variables
**Describe the bug**
Say we have this program: 
```
let {a, ..} = {a.b = 10 } in 
a[.]
```
We should get `b` as a completion, but in this case, we don't.

**Additional context**
This actually happens because the `RichTerm` associated with each pattern binding is not linearized.

### PR DESCRIPTION
**Pull request by ebresafegaga**
Currently, we can't get completion on variables bound by pattern matching, e.g:
```nickel
let {a, ..} = {a.b = 10 } in 
a[.]
```

With this change, we support completion for all variables (apart from variables bound by "rest" patterns) bound by a pattern deconstruction. This will work for both "context completion" and record completion. e.g:
```nickel 
let {Config, ..} = import "lib.ncl" in 
{
   data | Config = {
      [.]
   }
} 
```

Closes #1011

### CODE REVIEW

File: lsp/nls/src/linearization/building.rs [hunk 1]
```diff
@@ -162,8 +162,41 @@ impl<'b> Building<'b> {
                     .as_option()
                     .and_then(|value_index| self.get_item_kind(current_file, value_index))
             }
+            TermKind::Declaration(_, _, ValueState::Known(value), Some(idents)) => {
+                let item = self.get_item_kind(current_file, *value)?;
+                let item = self.resolve_reference(current_file, item)?;
+
+                let mut ids = idents.clone();
+                // (previous value, current value)
+                let mut result = (item, item);
```
Comment (yannham) [inline lsp/nls/src/linearization/building.rs:171]: IMHO it would be clearer to have two separate variables `prev_value` and `curr_value` (or whatever you call them) rather than using an anonymous tuple. Unless there is a good reason to do so (like calling a stdlib functions that expect a tuple or something).

File: lsp/nls/src/linearization/interface.rs [hunk 2]
```diff
@@ -24,7 +24,12 @@ impl ResolutionState for Resolved {}
 /// Can be extended later to represent Contracts, Records, etc.
 #[derive(Debug, Clone, PartialEq, Eq)]
 pub enum TermKind {
-    Declaration(Ident, Vec<ItemId>, ValueState),
+    Declaration(
+        Ident,
+        Vec<ItemId>,
+        ValueState,
+        /* pattern binding? */ Option<Vec<Ident>>,
```
[the remark this answers is not in the document]
Comment (ebresafegaga) [reply lsp/nls/src/linearization/interface.rs:31]: This is the path to a bound variable. E.g if we have `let { a = {b = {c, ..}, ..}, ..} = ... in ...`, the path will be `vec![a, b]`, and the ident will be `c`

File: lsp/nls/src/linearization/interface.rs [hunk 3]
```diff
@@ -24,7 +24,12 @@ impl ResolutionState for Resolved {}
 /// Can be extended later to represent Contracts, Records, etc.
 #[derive(Debug, Clone, PartialEq, Eq)]
 pub enum TermKind {
-    Declaration(Ident, Vec<ItemId>, ValueState),
+    Declaration {
+        id: Ident,
+        usages: Vec<ItemId>,
+        value: ValueState,
+        pattern_bindings: Option<Vec<Ident>>,
```
Comment (yannham) [inline lsp/nls/src/linearization/interface.rs:31]: Then, I think you should add what you just explained in an answer to my comment directly in the code, so that I'm not the only one to enjoy it :slightly_smiling_face: 

As a side note, `pattern_bindings` doesn't reflect what this variables really represent IMHO. There is a notion of `path`, so `path` should probably be in the name. There aren't bindings, because none but potentially the last element of the path is actually bound in the environment.

Comment (ebresafegaga) [reply lsp/nls/src/linearization/interface.rs:31]: Agreed. Thanks! 🙂

File: lsp/nls/src/linearization/building.rs [hunk 4]
```diff
@@ -162,10 +165,48 @@ impl<'b> Building<'b> {
...
+            TermKind::Declaration {
+                value: ValueState::Known(value),
+                path: Some(idents),
+                ..
+            } => {
+                let item = self.get_item_kind(current_file, *value)?;
+                let item = self.resolve_reference(current_file, item)?;
+
+                let mut ids = idents.clone();
+                // (previous value, current value)
```
Comment (yannham) [inline lsp/nls/src/linearization/building.rs:177]:
```suggestion
```

File: lsp/nls/src/linearization/building.rs [hunk 5]
```diff
@@ -162,10 +165,48 @@ impl<'b> Building<'b> {
...
+                let (mut prev_item, mut curr_item) = (item, item);
+                while let Some(id) = ids.pop() {
+                    match curr_item {
+                        TermKind::Record(ref fields) => {
+                            let item = fields.get(&id)?;
+                            let item = self.get_item_kind(current_file, *item)?;
```
Comment (yannham) [inline lsp/nls/src/linearization/building.rs:183]: Nitpick, but you're calling two things with different types with the same name (which is ok, sometimes, granted).

```suggestion
                            let item_kind = self.get_item_kind(current_file, *item)?;
```

File: lsp/nls/src/linearization/building.rs [hunk 6]
```diff
@@ -162,10 +165,48 @@ impl<'b> Building<'b> {
...
+                                    continue;
+                                }
+                                // the value from a record is always a record field
+                                _ => unreachable!(),
+                            }
+                        }
+                        _ => break,
+                    }
+                }
+                // return the `prev_item` becuase that was the record field we want to
```
Comment (yannham) [inline lsp/nls/src/linearization/building.rs:201]:
```suggestion
                // return the `prev_item` because that was the record field we wanted to
```

File: lsp/nls/src/linearization/building.rs [hunk 7]
```diff
@@ -162,10 +165,48 @@ impl<'b> Building<'b> {
...
+                // resolve, and `curr_item` points to the record field's value.
+                Some(prev_item)
             }
+            // if declaration is a let binding resolve its value
```
Comment (yannham) [inline lsp/nls/src/linearization/building.rs:205]:
```suggestion
            // if declaration is a let binding, resolve its value
```

**Review by yannham — APPROVED** [review]
