### PR TITLE
[LSP] Perform import resolution independently and provide diagnostics when a resolution fails

### LINKED ISSUE #1108: [LSP] Unresolved imports when one import resolution fails
**Describe the bug**
When we have more than one import term in a Nickel file, and one of those import fails to be resolved correctly, the other imports are automatically unresolved.

**Expected behavior**
The LSP *should* resolve all imports that have a correct Nickel file path, regardless of whether other imports resolve correctly.

### PR DESCRIPTION
**Pull request by ebresafegaga**
Currently, when we have multiple import terms in a file, and one of the imports fails to resolve without any errors, all the other imports automatically fail; this is not ideal for a good user experience. With this change, a single import resolution failure doesn't affect other import resolution, and the imports that fail are flagged out using the LSP's diagnostics feature.

Closes #1108

### CODE REVIEW

File: src/cache.rs [hunk 1]
```diff
@@ -659,14 +659,18 @@ impl Cache {
     /// corresponding source has been parsed.
     /// If resolved imports contain imports themselves, resolve them recursively.
     /// It returns a `Vec<FileId>`, which is a vector of all the imports that were transitively resolved.
+    #[allow(clippy::type_complexity)]
     pub fn resolve_imports(
         &mut self,
         file_id: FileId,
-    ) -> Result<CacheOp<Vec<FileId>>, CacheError<ImportError>> {
+        resillient: bool,
```
Comment (yannham) [inline src/cache.rs:666]: Please, no :cry:  we've had a lot of bugs (and still have, in fact) because of those pesky error-tolerance booleans that were present in each and every function of the cache, and it's really hard to keep track on what should be error tolerant or not. Now, there is a data `error_tolerance` or something in the cache that dictates the behavior.  There is an `ErrorTolerance` type. You should probably use it instead and not take any additional argument

File: src/transform/import_resolution.rs [hunk 2]
```diff
@@ -26,10 +27,50 @@ pub fn resolve_imports<R>(
     rt: RichTerm,
     resolver: &mut R,
 ) -> Result<(RichTerm, Vec<FileId>), ImportError>
+where
+    R: ImportResolver,
+{
+    let (term, resolved, errors) = resolve_imports_resillient(rt, resolver);
```
Comment (yannham) [inline src/transform/import_resolution.rs:33]:
```suggestion
    let (term, resolved, errors) = resolve_imports_resilient(rt, resolver);
```

File: src/transform/import_resolution.rs [hunk 3]
```diff
@@ -26,10 +27,50 @@ pub fn resolve_imports<R>(
...
+pub fn transform_one<R>(
+    rt: RichTerm,
+    resolver: &mut R,
+    parent: &Option<PathBuf>,
+) -> Result<RichTerm, ImportError>
+where
+    R: ImportResolver,
+{
+    let term = rt.as_ref();
+    match term {
```
Comment (yannham) [inline src/transform/import_resolution.rs:51]: Would that make sense to reuse `transform_one_resilient` here, as you did in `resolve_imports` using `resolve_imports_resilient`?

File: src/transform/import_resolution.rs [hunk 4]
```diff
@@ -40,41 +81,52 @@ where
...
-            Ok(RichTerm::new(Term::ResolvedImport(file_id), rt.pos))
-        }
-        _ => Ok(rt),
+        Term::Import(path) => match resolver.resolve(path, parent.clone(), &rt.pos) {
+            Ok((_, file_id)) => (RichTerm::new(Term::ResolvedImport(file_id), rt.pos), None),
+            Err(err) => (rt, Some(err)),
+        },
+        _ => (rt, None),
     }
 }
```
Comment (yannham) [inline src/transform/import_resolution.rs:132]: Suggestion: we have several function with similar names, the XXX, and the XXX_resilient. One way to organize this a bit more would be to have submodules, say `strict` and `tolerant` (just because it's the terminology we are already using in the cache; for what it's worth, resilient is totally fine too), each with their own `resolve_imports` and `transform_one` function.

File: src/cache.rs (hunk 1 above)
Comment (ebresafegaga) [reply src/cache.rs:666]: Right. This is much better. Thank you! 🙂

File: src/transform/import_resolution.rs (hunk 3 above)
Comment (ebresafegaga) [reply src/transform/import_resolution.rs:51]: Ah yes 👍

File: src/cache.rs [hunk 5]
```diff
@@ -682,10 +682,11 @@ impl Cache {
                     let parse_errs = parse_errs.clone();
```
Comment (yannham) [inline src/cache.rs:682]: It think the documentation of `resolve_imports` deserve to be updated, as you changed the return value, it's not in sync anymore.

File: src/transform/import_resolution.rs [hunk 6]
```diff
@@ -17,113 +16,133 @@ struct ImportsResolutionState<'a, R> {
...
+    /// * A `Vec<ImportError>`, telling the imports that couldn't be resolved.
+    pub fn resolve_imports<R>(
+        rt: RichTerm,
+        resolver: &mut R,
+    ) -> (RichTerm, Vec<FileId>, Vec<ImportError>)
+    where
+        R: ImportResolver,
+    {
+        let mut stack = Vec::new();
+        let mut unresolved = Vec::new();
```
Comment (yannham) [inline src/transform/import_resolution.rs:88]: Small nitpick: `unresolved` makes it sound this is a vector of `FileId` for unresolved imports. I think it's rather a vector of `parse_errors`?

File: src/transform/import_resolution.rs [hunk 7]
```diff
@@ -17,113 +16,133 @@ struct ImportsResolutionState<'a, R> {
...
-    });
+    /// Performs imports resolution for each import term independent from others.
+    /// It returns back a triple, containing:
+    /// * A `RichTerm` which may still contain unresolved imports.
+    /// * A `Vec<FileId>`, telling the imports which were resolved.
+    /// * A `Vec<ImportError>`, telling the imports that couldn't be resolved.
+    pub fn resolve_imports<R>(
+        rt: RichTerm,
+        resolver: &mut R,
+    ) -> (RichTerm, Vec<FileId>, Vec<ImportError>)
```
Comment (yannham) [inline src/transform/import_resolution.rs:83]: Nitpick: could use a proper struct for the return type.

**Review by yannham — APPROVED** [review]

**Comment by yannham** [comment]
The benchmarks are broken, because they referred to `import_resolution::some_function_that_doesnt_exist_anymore`, I reckon.
