### PR TITLE
Give a better error message when trying to query a non-record

### LINKED ISSUE #1292: Trying to query something that isn't a record gives suboptimal error message
**Describe the bug**
When trying to query a value that isn't a record, either at top-level, or because you specify a field path that isn't valid, Nickel gives a dynamic type error that might point to some internals, in particular if the faulty value has a contract attached.

**To Reproduce**

```text
nickel>  let config | String -> {..} = fun value_param => { value = value_param }
nickel> :query config value
error: dynamic type error
   ┌─ <stdlib/internals.ncl>:24:7
   │
24 │       (fun x => %assume% codomain (%go_codom% label) (value (%assume% domain (%chng_pol% (%go_dom% label)) x)))
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this expression has type Function, but Record was expected
   │
   = query
```

**Expected behavior**
The query evaluation code should check by itself that the result has the right type before proceeding further, in order to show a tailored error message.

### PR DESCRIPTION
**Pull request by jneem**
The first commit is a simple bug fix: the error position should point to the un-evaluated term. This is consistent with what happens for later elements in the path.

The second commit adds a special error variant for querying fields of non-records.

Fixes #1292

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -1153,6 +1162,26 @@ impl IntoDiagnostics<FileId> for EvalError {
...
+                let label = format!(
+                    "tried to query field `{}`, but the expression has type {}",
+                    id,
+                    value
+                        .term
+                        .type_of()
+                        .unwrap_or_else(|| String::from("<unevaluated>")),
+                );
+
+                let labels = if let Some(span) = pos.into_opt() {
```
Comment (yannham) [inline src/error.rs:1175]: (very) minor nitpick: if `vec![..]` is applied in both branches, you might as well factor it out, defining `let label = ...` as a single label and using `vec![label]` in `with_labels` below. It'll save a staggering number of 7 characters!

**Review by yannham — APPROVED** [review]
LGTM!
