### PR TITLE
[Fix] Fix bad lexing of mutline string closing delimiter

### LINKED ISSUE #1429: Wrong parsing of multiline string ending as an interpolation sequence
**Describe the bug**

If a closing delimiter of a multiline string is followed by zero or more `%` and a final `{`, it is unduly parsed (or should I say lexed, in this case) as an interpolation sequence instead of a closing delimiter.

**To Reproduce**

```nickel
nickel> m%%""%%%{std.to_string 1}" World"%%
"\"%1\" World"

```

**Expected behavior**
The previous program should fail with a syntax error, as it is an empty string `m%%""%%` followed by gibberish. 

**Environment**
 - Version of the code: ec3b9c4a35bced37d321a01636b80b4f91533924

**Additional context**

The example comes from a test. I suspect that when the closing delimiter of multiline strings was `"%m` (pre 1.0), lexing `"%{` correctly implied to favor string interpolation over a potential end of a string (as the presence of `{` was disqualifying the whole sequence as a closing delimiter). This code has stayed the same, but now we don't have a trailing `m` anymore, and `"%` must be treated as a closing delimiter, no matter what comes next. See https://github.com/tweag/topiary/issues/547#issuecomment-1618430667.

### PR DESCRIPTION
**Pull request by yannham**
Closes #1429.

We introduced a hack in the lexer because of a Logo issue related backtracking. Pre Nickel 1.0, the problem was related to strings like:

```nickel
let x = "string" in m%%"some "%%{x}"%%m
```

Here, `"%%{x}` had to be interpreted as a double quote `"` followed by an interpolation sequence `%%{`. Backtracking during matching is required, because up to `{`, we don't know yet if we are lexing an end delimiter `"%%m` or a `"` followed by an interpolation sequence. Logos doesn't handle those well (see https://github.com/maciejhirsz/logos/issues/200). So we added another token for this "ambiguous" (not literally) sequence, the `CandidateQuoteInterpolation`. However, now that that the final `m` is not required, a sequence of the form `"%%{` is either an end delimiter followed by a normal, non-string token `{` (if there's as many `%` as in the opening delimiter), a "closing delimiter too long" if there's more `%` than in the opening delimiter), or otherwise a verbatim `"%%{` (if there's less `%` than in the opening delimiter). This can _never_ be interpreted as a double quote followed by an interpolated sequence.

Thus, we can get rid of the ad-hoc `CandidateQuoteInterpolation` and related special treatments. This also get rid of regression tests, because this subtlety had caused several issues in the past but they are now moot given the new 1.0 syntax.

### CODE REVIEW

File: core/src/parser/lexer.rs [hunk 1]
```diff
@@ -467,8 +461,10 @@ pub enum ModalLexer<'input> {
     MultiString {
         mode_data: MultiStrData,
         /// A token that has been buffered and must be returned at the next call to `next()`. This is
-        /// made necessary by an issue of Logos (<https://github.com/maciejhirsz/logos/issues/200>). See
-        /// [`MultiStringToken::QuotesCandidateInterpolation`].
+        /// related to lexing an possible interpolation sequence, such as `%%%{`, which requires to
+        /// split a candidate interpolation token in two. In this case, we need to emit the first
+        /// token on the spot, and bufferize the second one, to be emitted on the following call to
```
Comment (jneem) [inline core/src/parser/lexer.rs:466]:
```suggestion
        /// token on the spot, and buffer the second one, to be emitted on the following call to
```

**Review by jneem — APPROVED** [review]

File: core/src/parser/lexer.rs (hunk 1 above)
Comment (jneem) [reply core/src/parser/lexer.rs:466]: I guess I can't argue with wiktionary :shrug:
