### PR TITLE
[Fix] Typing of stdlib items annotated with a contract

### LINKED ISSUE #700: Stdlib functions with contract annotation don't have the right type
**Describe the bug**
Stdlib functions which have contract annotation in place of static type annotations end up with the type `Dyn` in the interface of the module. For example:

```console
nickel>:typecheck builtin
Ok: {
  serialize: Dyn,
  hash: Dyn, 
  is_str: Dyn -> Bool, 
  ValueType: Dyn,
  is_record: Dyn -> Bool,
  deep_seq: forall a. Dyn -> a -> a,
  deserialize: Dyn, HashAlgorithm: Dyn,
  seq: forall a. Dyn -> a -> a, typeof: Dyn,
  ExportFormat: Dyn, is_array: Dyn -> Bool,
  is_fun: Dyn -> Bool, is_bool: Dyn -> Bool,
  is_num: Dyn -> Bool
}
```

While querying say, `serialize`, shows that it has a much more precise annotation:

```console
nickel>:q builtin.serialize
• contract: ExportFormat -> Dyn -> Str
[..]
```

**To Reproduce**
One easy way to get bugged by this issue is to just try to use such functions in a typed context:

```console
nickel>let data = {foo = "bar"} in
let as_json : Str = builtin.serialize `Json data in
as_json

error: incompatible types
  ┌─ repl-input-6:2:21
  │
2 │ let as_json : Str = builtin.serialize `Json data in
  │                     ^^^^^^^^^^^^^^^^^ this expression
  │
  = The type of the expression was expected to be `_a -> _b -> Str`
  = The type of the expression was inferred to be `Dyn`
  = These types are not compatible
```
  

**Expected behavior**
The stdlib items annotated with contracts should have their type properly inferred.

**Additional context**
The fault lies, with high probability, in the function `typecheck::infer_type`, that do its magic to bubble up the types from the record fields to the top-level record.

### PR DESCRIPTION
**Pull request by yannham**
Fix #700. However, require a fix to #701 which currently causes tests to fail (and any meaningful test that we can think of, unfortunately, will have the same issue) before getting green CI and being mergeable.

### CODE REVIEW

File: src/typecheck/mod.rs [hunk 1]
```diff
@@ -1042,23 +1042,30 @@ pub fn apparent_type(
...
+            types, contracts, ..
+        }) if (types.is_some() || !contracts.is_empty()) => apparent_type(t, None, None).into(),
+        // We unwrap meta-values without any type information. Otherwise, something like a
+        // top-level module documentation would stop this function from doing its job.
+        Term::MetaValue(MetaValue {
+            value: Some(rt),
+            types: None,
+            contracts,
+            ..
+        }) if contracts.is_empty() => infer_record_type(rt.as_ref()),
```
Comment (fuzzypixelz) [inline src/typecheck/mod.rs:1058]: Shouldn't this be `if types.is_none() && contracts.is_empty()` instead?

**Review by fuzzypixelz — APPROVED** [review]
LGTM.

File: src/typecheck/mod.rs (hunk 1 above)
Comment (yannham) [reply src/typecheck/mod.rs:1058]: Ah, good catch!

Comment (yannham) [reply src/typecheck/mod.rs:1058]: In fact, it's already covered by the pattern `types: None`, because types is just an option.
