### PR TITLE
Don't panic when a row mismatch occurs while unifying row tails

### LINKED ISSUE #841: Panic in `typechecker::unify_rows()`
**Describe the bug**

The typechecker panics 30-50% of the time while checking a function with a type error. Presumably this isn't happening to every function, but it's certainly happening in the `split` example included below.

The output is:

```text
thread 'main' panicked at 'typechecker::unify_rows(): unexpected error while unifying row tails 
RowMismatch(
  Ident { 
    label: "key", 
    pos: Original(RawSpan { src_id: FileId(1), start: ByteIndex(239), end: ByteIndex(242) }) 
  }, 
  Concrete(RowExtend(
    Ident { 
      label: "key", 
      pos: Original(RawSpan { src_id: FileId(1), start: ByteIndex(239), end: ByteIndex(242) }) 
    },
    Some(Ptr(26)), 
    Ptr(27)
  )), 
  Concrete(RowExtend(
    Ident { 
      label: "key", 
      pos: Original(RawSpan { src_id: FileId(1), start: ByteIndex(30), end: ByteIndex(33) }) 
    },
    Some(Concrete(Str)), 
    Concrete(RowEmpty)
  )), 
  TypeMismatch(Concrete(Array(Ptr(22))), Concrete(Str))
)', src/typecheck/mod.rs:1415:28
```

**To Reproduce**

This can be reproduced with a relatively small example adapted from the `correctness` docs:

```nickel
# lib.ncl
{
  split : forall a. Array { key: Str, value: a } -> { keys: Array Str, values: Array a } = fun pairs =>
    array.fold (fun pair acc =>
      {
        # problem: the right expression to use is `[pair.key]`
        keys = acc.keys @ pair.key
        values = acc.values @ [pair.value]
      })
      { keys = [], values = [] }
      pairs
}
```

**Expected behavior**

Running `nickel -f lib.ncl` produces a type error. Currently this happens slightly more than half the time (in my rough estimation). The error is:

```text
error: incompatible rows declaration
   ┌─ /home/matthew/code/playground/learn-nickel/lib.ncl:10:7
   │
10 │       pairs
   │       ^^^^^ this expression
   │
   = The type of the expression was expected to be `{key: Array Str, value: a ; _a}`
   = The type of the expression was inferred to be `{key: Str, value: a}`
   = Could not match the two declaration of `key`

error: While typing field `key`: incompatible types
 = The type of the expression was expected to be `Array Str`
 = The type of the expression was inferred to be `Str`
 = These types are not compatible
```

**Environment**
 - OS name + version: NixOS
 - Version of the code: Nickel 0.2.1

**Additional context**

Running with `RUST_BACKTRACE=full` produces the following output:

```text
stack backtrace:
   0:     0x5566dff9b56c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb16b437de6ab6276
   1:     0x5566dffcc73e - core::fmt::write::h8f8bef23583ee234
   2:     0x5566dffa3761 - std::io::Write::write_fmt::h8486efe074824056
   3:     0x5566dffab6ae - std::panicking::default_hook::{{closure}}::hdfa4615b29a34cb8
   4:     0x5566dffab317 - std::panicking::default_hook::h60ffd169fe7df297
   5:     0x5566dffabbc1 - std::panicking::rust_panic_with_hook::hf0183b899953e185
   6:     0x5566dff9c167 - std::panicking::begin_panic_handler::{{closure}}::h93eac1c61f0beba3
   7:     0x5566dff9b944 - std::sys_common::backtrace::__rust_end_short_backtrace::he4788588c206eaab
   8:     0x5566dffab872 - rust_begin_unwind
   9:     0x5566dfc1ef63 - core::panicking::panic_fmt::h20a31c8e90ca0d37
  10:     0x5566dfd085d3 - core::result::Result<T,E>::map_err::h002440d991987931
  11:     0x5566dfd2fd13 - nickel_lang::typecheck::unify_rows::hc508cbed036074cd
  12:     0x5566dfd2e4b6 - nickel_lang::typecheck::unify::h68f6c55c4b05b7c3
  13:     0x5566dfd2d232 - nickel_lang::typecheck::unify::h68f6c55c4b05b7c3
  14:     0x5566dfd1f84d - nickel_lang::typecheck::type_check_::h4f4c79ce9d6525b0
  15:     0x5566dfd20df1 - nickel_lang::typecheck::type_check_::h4f4c79ce9d6525b0
  16:     0x5566dfd20a81 - nickel_lang::typecheck::type_check_::h4f4c79ce9d6525b0
  17:     0x5566dfd1a67b - nickel_lang::typecheck::walk::h2c282511348455e0
  18:     0x5566dfd8a88f - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::he21490e4f64872a8
  19:     0x5566dfd3a3f0 - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold::hbd156106715e93ea
  20:     0x5566dfd1b554 - nickel_lang::typecheck::walk::h2c282511348455e0
  21:     0x5566dfd17626 - nickel_lang::typecheck::type_check::h8334863019f100b9
  22:     0x5566dfcd243c - nickel_lang::cache::Cache::typecheck::h408242d4854a460f
  23:     0x5566dfcd28f1 - nickel_lang::cache::Cache::typecheck::h408242d4854a460f
  24:     0x5566dfcd5387 - nickel_lang::cache::Cache::prepare::h24a3fc65a254866b
  25:     0x5566dfcfbd5b - nickel_lang::program::Program::prepare_eval::hcdb4122cbda4b5a2
  26:     0x5566dfcfc0a1 - nickel_lang::program::Program::eval_full::h774cbe96a40c3c7e
  27:     0x5566dfc41055 - nickel::main::h4e598c0df1f6db50
  28:     0x5566dfc2d843 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc86a185db3e33a47
  29:     0x5566dfc390b9 - std::rt::lang_start::{{closure}}::h339f8701c56045eb
  30:     0x5566dffa3075 - std::rt::lang_start_internal::h3e617fbe87035bdb
  31:     0x5566dfc42ac2 - main
  32:     0x7fc5b86b924e - __libc_start_call_main
  33:     0x7fc5b86b9309 - __libc_start_main@@GLIBC_2.34
  34:     0x5566dfc1f105 - _start
  35:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by matthew-healy**
When unifying the tails of row types, we only handle a subset of all
possible unification errors. Previously row mismatches were not handled,
however in certain cases (such as the included test case here) we end up
trying to unify a row tail with a unification variable which resolves to
a type which doesn't match, which resulted in a panic. This commit
handles that error, preventing the panic.

This fixes #841.

### CODE REVIEW

File: tests/typecheck_fail.rs [hunk 1]
```diff
@@ -197,6 +198,24 @@ fn polymorphic_row_constraints() {
...
 
+/// Regression test following [#841](https://github.com/tweag/nickel/issues/841).
+/// Checks that type mismatches occurring in the tail of a row type with
+/// unification variables don't cause a panic.
+#[test]
+fn row_type_unification_variable_mismatch() {
+    use nickel_lang::error::Error;
+
+    // We run the example multiple times as the order in which row types
+    // are checked is not deteministic, and failures are handled differently
```
Comment (yannham) [inline tests/typecheck_fail.rs:209]:
```suggestion
    // are checked is not deterministic, and failures are handled differently
```

**Review by yannham — APPROVED** [review]
